name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101        
    - name: catalog current
      run: type -a pwd
    - name: Install dependencies
      working-directory : ./prt.griphit.api/prt.graphit.sku.api
      run: dotnet restore
    - name: Build
      working-directory : ./prt.griphit.api/prt.graphit.sku.api
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory : ./prt.griphit.api/prt.graphit.sku.api
      run: dotnet test --no-restore --verbosity normal
